print ("This is my first code I am sharing")
print ("This is my first code I am sharing")
print ("This is my first code I am sharing")
print ("This is my first code I am sharing")
print ("This is my first code I am sharing")
